prompt Importing table MENU...
set feedback off
set define off
insert into MENU (MEN_CLAVE, MEN_NOMBRE, MEN_ICONO, MEN_IMAGEN, MEN_ATTRR_VALUE, MEN_NIVEL, MEN_TARGET, MEN_TIPO)
values (3, '03-Administracion de Usuarios', 'fa-user', 'fa-user', null, 2, 4, 1);

insert into MENU (MEN_CLAVE, MEN_NOMBRE, MEN_ICONO, MEN_IMAGEN, MEN_ATTRR_VALUE, MEN_NIVEL, MEN_TARGET, MEN_TIPO)
values (2, '06-MARCAR ENTRADA', 'fa-user', 'fa-user', null, 2, 6, 1);

insert into MENU (MEN_CLAVE, MEN_NOMBRE, MEN_ICONO, MEN_IMAGEN, MEN_ATTRR_VALUE, MEN_NIVEL, MEN_TARGET, MEN_TIPO)
values (1, 'MANTENIMIENTO', 'fa-user', null, null, 1, 1, 1);

insert into MENU (MEN_CLAVE, MEN_NOMBRE, MEN_ICONO, MEN_IMAGEN, MEN_ATTRR_VALUE, MEN_NIVEL, MEN_TARGET, MEN_TIPO)
values (11, '03-CONSULTA DE MIEMBROS DE GUARDIA', null, null, null, 2, 3, 2);

insert into MENU (MEN_CLAVE, MEN_NOMBRE, MEN_ICONO, MEN_IMAGEN, MEN_ATTRR_VALUE, MEN_NIVEL, MEN_TARGET, MEN_TIPO)
values (4, '04-AGREGAR CALIFICACION', null, null, null, 2, 7, 1);

insert into MENU (MEN_CLAVE, MEN_NOMBRE, MEN_ICONO, MEN_IMAGEN, MEN_ATTRR_VALUE, MEN_NIVEL, MEN_TARGET, MEN_TIPO)
values (5, '05-CREAR GRUPOS DE GUARDIA', null, null, null, 2, 11, 1);

insert into MENU (MEN_CLAVE, MEN_NOMBRE, MEN_ICONO, MEN_IMAGEN, MEN_ATTRR_VALUE, MEN_NIVEL, MEN_TARGET, MEN_TIPO)
values (6, 'CONSULTA', null, null, null, 1, null, 2);

insert into MENU (MEN_CLAVE, MEN_NOMBRE, MEN_ICONO, MEN_IMAGEN, MEN_ATTRR_VALUE, MEN_NIVEL, MEN_TARGET, MEN_TIPO)
values (7, '12-CONSULTA DE MARCACION', null, null, null, 2, 12, 2);

insert into MENU (MEN_CLAVE, MEN_NOMBRE, MEN_ICONO, MEN_IMAGEN, MEN_ATTRR_VALUE, MEN_NIVEL, MEN_TARGET, MEN_TIPO)
values (8, '08-TIPO DE PERSONA', null, null, null, 2, 13, 1);

insert into MENU (MEN_CLAVE, MEN_NOMBRE, MEN_ICONO, MEN_IMAGEN, MEN_ATTRR_VALUE, MEN_NIVEL, MEN_TARGET, MEN_TIPO)
values (9, '09-RANGO DE LOS VOLUNTARIOS', null, null, null, 2, 15, 1);

insert into MENU (MEN_CLAVE, MEN_NOMBRE, MEN_ICONO, MEN_IMAGEN, MEN_ATTRR_VALUE, MEN_NIVEL, MEN_TARGET, MEN_TIPO)
values (10, '10-MANTENIMIENTO DE PERSONA', null, null, null, 2, 17, 1);

insert into MENU (MEN_CLAVE, MEN_NOMBRE, MEN_ICONO, MEN_IMAGEN, MEN_ATTRR_VALUE, MEN_NIVEL, MEN_TARGET, MEN_TIPO)
values (12, '20-GRUPOS DE GUARDIA', null, null, null, 2, 20, 2);

insert into MENU (MEN_CLAVE, MEN_NOMBRE, MEN_ICONO, MEN_IMAGEN, MEN_ATTRR_VALUE, MEN_NIVEL, MEN_TARGET, MEN_TIPO)
values (13, '21-CONSULTA DE CALIFICACIONES', null, null, null, 2, 21, 2);

prompt Done.
